use strict;
use warnings;
use Test::More;
use ok 'FizzBuzz';
is(FizzBuzz::fizzbuzz(1), '1', '1 ok');
is(FizzBuzz::fizzbuzz(3), 'fizz\n', '3 ok');
is(FizzBuzz::fizzbuzz(5), 'buzz\n', '5 ok');
is(FizzBuzz::fizzbuzz(6), 'fizz\n', '6 ok');
is(FizzBuzz::fizzbuzz(15), 'fizzbuzz\n', '15 ok');
done_testing();
